version: "3"
services:
  demomongodb:
    image: mongo:latest
    container_name: "demomongodb"
    ports:
      - 27017:27017
  demoapp:
    image: 883630/demoapp:v1
    container_name: demoapp
    ports:
      - 8080:8080
    links:
      - demomongodb